[metadata]
name = ohlc-client
version = attr: ohlc.__version__
description = Batch-oriented network and embedded interfaces for ohlc
url = https://github.com/cy-chengyan/ohlc
project_urls =
    Source = https://github.com/cy-chengyan/ohlc
    Issues = https://github.com/cy-chengyan/ohlc/issues
license = Apache-2.0
license_files = LICENSE

[options]
packages = find:
python_requires = >=3.9

[options.packages.find]
include = ohlc*
